# version: "3"

# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - my_postgres_volume:/var/lib/docker/volumes/my_postgres_volume/_data

#   web:
#     build: .
#     command: >
#       sh -c "
#         python manage.py collectstatic --noinput &&
#         python manage.py makemigrations &&
#         python manage.py migrate &&
#         python manage.py runserver 0.0.0.0:8000
#       "
#     volumes:
#       - .:/code
#       - static_volume:/code/staticfiles
#       - media_volume:/code/mediafiles
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     env_file:
#       - .env

# volumes:
#   my_postgres_volume:
#   static_volume:
#   media_volume:

version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - a-backend-system-for-an-online-learning-platform_my_postgres_volume:/var/lib/postgresql/data

volumes:
  a-backend-system-for-an-online-learning-platform_my_postgres_volume:
